/* Order status pill — tones from OrderStatus; copy via t('status.*'). */
import { t, type I18nKey } from '@/i18n';
import { Pill } from './ui';

/* Order status → pill mapping (statuses from OrderStatus; copy via t('status.*')). */
const STATUS_TONE: Record<string, 'danger' | 'warning' | 'info' | 'success' | 'neutral'> = {
  draft: 'neutral',
  requested: 'warning',
  pending_payment: 'warning',
  paid: 'info',
  merchant_accepted: 'info',
  preparing: 'warning',
  rider_assigned: 'info',
  picked_up: 'info',
  delivering: 'info',
  delivered: 'success',
  completed: 'success',
  cancelled: 'danger',
  refunded: 'success',
  failed: 'danger',
  disputed: 'danger',
  in_progress: 'info',
  quote_required: 'warning',
  quote_submitted: 'warning',
  quote_accepted: 'success',
  provider_requested: 'info',
  provider_accepted: 'info',
  scheduled: 'info',
  awaiting_customer_confirmation: 'warning',
  declined: 'danger',
  no_show: 'warning',
  en_route: 'info',
  provider_arrived: 'info',
  completion_review: 'info',
  open: 'info',
  billing: 'warning',
  closed: 'neutral',
  pending: 'warning',
  confirmed: 'success',
  seated: 'info',
  unused: 'success',
  active: 'success',
  used: 'info',
  redeemed: 'info',
  expired: 'neutral',
  void: 'danger',
  live: 'success',
  ended: 'neutral',
  delisted: 'neutral',
  rejected: 'danger',
  pending_review: 'warning',
  extended: 'info',
  validating: 'info',
  matching: 'info',
  offered: 'info',
  reminder_sent: 'info',
  check_in: 'info',
  diagnosing: 'warning',
  settled: 'success',
  warranty: 'info',
  failed_delivery: 'danger',
  rescheduled: 'warning',
  returning: 'info',
  rider_arrived_pickup: 'info',
  rider_arrived_dropoff: 'info',
  timed_out: 'warning',
  processing: 'info',
  exception: 'danger',
};

export function StatusPill({ status }: { status: string }) {
  const tone = STATUS_TONE[status] ?? 'neutral';
  return <Pill label={t(`status.${status}` as I18nKey)} tone={tone} />;
}
