import { adminListStaffRoles } from '@hudumika/contract'

export interface StaffRoleDef {
  id: string
  name: string
  permissions: string[]
}

export const STAFF_ROLES: StaffRoleDef[] = [
  {
    id: 'platform-owner',
    name: 'Platform Owner',
    permissions: ['*'],
  },
  {
    id: 'platform-administrator',
    name: 'Platform Administrator',
    permissions: [
      'order.read',
      'order.cancel',
      'order.refund',
      'order.override',
      'shipment.read',
      'shipment.reassign',
      'shipment.hold',
      'shipment.release',
      'dispatch.read',
      'dispatch.assign',
      'dispatch.reassign',
      'provider.read',
      'provider.verify',
      'provider.suspend',
      'merchant.read',
      'merchant.approve',
      'merchant.suspend',
      'finance.read',
      'finance.refund',
      'finance.payout_adjust',
      'risk.investigate',
      'risk.block',
      'configuration.edit',
      'iam.manage',
      'audit.read',
      'refund.approve',
      'review.moderate',
      'group_buy.moderate',
      'promotion.moderate',
      'voucher.verify',
      'conversation.read',
      'conversation.block',
      'chain.read',
      'chain.suspend',
      'webhook.read',
      'webhook.retry',
      'export.request',
      'export.approve',
      'cod.read',
      'cod.reconcile',
      'safety.read',
      'safety.respond',
      'fleet.read',
      'fleet.admin',
      'hub.read',
      'hub.manage',
      'consignment.read',
      'consignment.resolve',
      'handoff.read',
      'handoff.resolve',
      'waybill.read',
      'trip.read',
      'reconciliation.read',
      'reconciliation.resolve',
      'anomaly.read',
      'anomaly.resolve',
      'warehouse.read',
      'warehouse.manage',
      'carrier.read',
      'carrier.manage',
      'facility.read',
      'facility.manage',
      'exception.read',
      'exception.resolve',
      'customer.suspend',
      'user.suspend',
      'feature.edit',
      'analytics.read',
      'approval.decide',
    ],
  },
  {
    id: 'operations-manager',
    name: 'Operations Manager',
    permissions: [
      'order.read',
      'order.cancel',
      'order.refund',
      'order.override',
      'shipment.read',
      'shipment.reassign',
      'shipment.hold',
      'shipment.release',
      'dispatch.read',
      'dispatch.assign',
      'dispatch.reassign',
      'provider.read',
      'provider.verify',
      'provider.suspend',
      'merchant.read',
      'merchant.suspend',
      'finance.read',
      'finance.refund',
      'risk.investigate',
      'risk.block',
      'configuration.edit',
      'audit.read',
      'refund.approve',
      'review.moderate',
      'group_buy.moderate',
      'promotion.moderate',
      'conversation.read',
      'chain.read',
      'chain.suspend',
      'webhook.read',
      'export.request',
      'safety.read',
      'safety.respond',
      'fleet.read',
      'fleet.admin',
      'hub.read',
      'hub.manage',
      'consignment.read',
      'consignment.resolve',
      'handoff.read',
      'handoff.resolve',
      'waybill.read',
      'trip.read',
      'reconciliation.read',
      'reconciliation.resolve',
      'anomaly.read',
      'anomaly.resolve',
      'warehouse.read',
      'warehouse.manage',
      'carrier.read',
      'carrier.manage',
      'facility.read',
      'facility.manage',
      'exception.read',
      'exception.resolve',
      'customer.suspend',
      'user.suspend',
      'feature.edit',
      'approval.decide',
    ],
  },
  {
    id: 'dispatch-manager',
    name: 'Dispatch Manager',
    permissions: [
      'order.read',
      'order.cancel',
      'order.override',
      'shipment.read',
      'shipment.reassign',
      'dispatch.read',
      'dispatch.assign',
      'dispatch.reassign',
      'provider.read',
      'merchant.read',
      'fleet.read',
      'hub.read',
    ],
  },
  {
    id: 'regional-operations-manager',
    name: 'Regional Operations Manager',
    permissions: [
      'order.read',
      'order.cancel',
      'order.refund',
      'order.override',
      'shipment.read',
      'shipment.reassign',
      'shipment.hold',
      'shipment.release',
      'dispatch.read',
      'dispatch.assign',
      'dispatch.reassign',
      'provider.read',
      'provider.verify',
      'provider.suspend',
      'merchant.read',
      'merchant.suspend',
      'finance.read',
      'finance.refund',
      'risk.investigate',
      'risk.block',
      'configuration.edit',
      'audit.read',
      'refund.approve',
      'review.moderate',
      'group_buy.moderate',
      'promotion.moderate',
      'conversation.read',
      'chain.read',
      'chain.suspend',
      'webhook.read',
      'export.request',
      'safety.read',
      'safety.respond',
      'fleet.read',
      'fleet.admin',
      'hub.read',
      'hub.manage',
      'consignment.read',
      'consignment.resolve',
      'handoff.read',
      'handoff.resolve',
      'waybill.read',
      'trip.read',
      'reconciliation.read',
      'reconciliation.resolve',
      'anomaly.read',
      'anomaly.resolve',
      'warehouse.read',
      'warehouse.manage',
      'carrier.read',
      'carrier.manage',
      'facility.read',
      'facility.manage',
      'exception.read',
      'exception.resolve',
      'customer.suspend',
      'user.suspend',
      'feature.edit',
      'approval.decide',
    ],
  },
  {
    id: 'merchant-operations',
    name: 'Merchant Operations',
    permissions: [
      'order.read',
      'merchant.read',
      'merchant.approve',
      'merchant.suspend',
      'finance.read',
      'chain.read',
    ],
  },
  {
    id: 'provider-operations',
    name: 'Provider Operations',
    permissions: ['order.read', 'provider.read', 'provider.verify', 'provider.suspend', 'finance.read'],
  },
  {
    id: 'rider-operations',
    name: 'Rider Operations',
    permissions: [
      'order.override',
      'shipment.read',
      'dispatch.read',
      'provider.read',
      'provider.verify',
      'provider.suspend',
      'cod.read',
      'cod.reconcile',
      'safety.read',
      'fleet.read',
      'fleet.admin',
      'consignment.read',
    ],
  },
  {
    id: 'customer-support',
    name: 'Customer Support',
    permissions: [
      'order.read',
      'order.cancel',
      'order.refund',
      'dispatch.read',
      'dispatch.reassign',
      'merchant.read',
      'refund.approve',
      'review.moderate',
      'conversation.read',
      'conversation.block',
      'voucher.verify',
      'customer.suspend',
      'user.suspend',
    ],
  },
  {
    id: 'finance',
    name: 'Finance',
    permissions: [
      'order.read',
      'order.cancel',
      'order.refund',
      'provider.read',
      'merchant.read',
      'finance.read',
      'finance.refund',
      'finance.payout_adjust',
      'audit.read',
      'audit.unmask',
      'refund.approve',
      'export.request',
      'export.approve',
      'cod.read',
      'cod.reconcile',
      'chain.read',
      'analytics.read',
      'reconciliation.read',
      'reconciliation.resolve',
    ],
  },
  {
    id: 'payments',
    name: 'Payments',
    permissions: ['order.read', 'order.refund', 'provider.read', 'merchant.read', 'finance.read', 'finance.refund', 'refund.approve', 'audit.read'],
  },
  {
    id: 'risk-and-fraud',
    name: 'Risk & Fraud',
    permissions: [
      'order.read',
      'dispatch.read',
      'provider.read',
      'provider.suspend',
      'merchant.read',
      'finance.read',
      'risk.investigate',
      'risk.block',
      'approval.decide',
    ],
  },
  {
    id: 'trust-and-safety',
    name: 'Trust & Safety',
    permissions: [
      'order.read',
      'dispatch.read',
      'provider.read',
      'risk.investigate',
      'risk.block',
      'provider.suspend',
      'review.moderate',
      'conversation.read',
      'conversation.block',
      'safety.read',
      'safety.respond',
      'customer.suspend',
      'user.suspend',
    ],
  },
  {
    id: 'compliance',
    name: 'Compliance',
    permissions: [
      'order.read',
      'shipment.read',
      'shipment.hold',
      'shipment.release',
      'provider.read',
      'merchant.read',
      'finance.read',
      'risk.investigate',
      'audit.read',
      'audit.unmask',
      'review.moderate',
      'conversation.read',
      'export.request',
      'export.approve',
      'handoff.read',
      'waybill.read',
      'anomaly.read',
      'exception.read',
      'approval.decide',
    ],
  },
  {
    id: 'marketing',
    name: 'Marketing',
    permissions: ['finance.read', 'merchant.read', 'promotion.moderate', 'group_buy.moderate'],
  },
  {
    id: 'analytics',
    name: 'Analytics',
    permissions: [
      'order.read',
      'merchant.read',
      'finance.read',
      'audit.read',
      'export.request',
      'analytics.read',
    ],
  },
  {
    id: 'content-manager',
    name: 'Content Manager',
    permissions: ['merchant.read', 'audit.read', 'configuration.edit', 'promotion.moderate', 'group_buy.moderate'],
  },
  {
    id: 'technical-operations',
    name: 'Technical Operations',
    permissions: [
      'configuration.edit',
      'audit.read',
      'webhook.read',
      'webhook.retry',
      'fleet.admin',
      'feature.edit',
    ],
  },
  {
    id: 'security-administrator',
    name: 'Security Administrator',
    permissions: ['iam.manage', 'audit.read', 'approval.decide'],
  },
  {
    id: 'read-only-auditor',
    name: 'Read-only Auditor',
    permissions: ['audit.read'],
  },
]

let loadedRoles: StaffRoleDef[] | null = null

export function getLoadedRoles(): StaffRoleDef[] | null {
  return loadedRoles
}

export async function loadStaffRoles(): Promise<StaffRoleDef[]> {
  try {
    const res = await adminListStaffRoles()
    if (res.status === 200) {
      const roles: StaffRoleDef[] = res.data.map((r) => ({
        id: r.id ?? r.name,
        name: r.name,
        permissions: r.permissions,
      }))
      loadedRoles = roles
      return roles
    }
  } catch {
    // fall through to static
  }
  return STAFF_ROLES
}

export function effectiveRoles(): StaffRoleDef[] {
  return loadedRoles ?? STAFF_ROLES
}

export function rolePermissions(roleId: string): string[] {
  const all = effectiveRoles()
  const def = all.find((r) => r.id === roleId)
  return def ? [...def.permissions] : []
}

export function allPermissionKeys(): string[] {
  const keys = new Set<string>()
  for (const role of effectiveRoles()) {
    if (role.permissions.includes('*')) continue
    for (const permission of role.permissions) keys.add(permission)
  }
  return [...keys].sort()
}
