-- +goose Up
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS pair_code_ttl_minutes int DEFAULT 10;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS birthday_reward_window_days int DEFAULT 30;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS masked_call_ttl_minutes int DEFAULT 5;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS masked_call_gateway_timeout_seconds int DEFAULT 10;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS payment_qr_ttl_minutes int DEFAULT 15;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS throttle_max_attempts int DEFAULT 10;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS throttle_window_minutes int DEFAULT 15;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS check_in_rate_limit int DEFAULT 1;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS check_in_rate_window_hours int DEFAULT 24;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS check_in_redis_ttl_hours int DEFAULT 48;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS dispatch_offer_expiry_minutes int DEFAULT 15;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS default_campaign_duration_days int DEFAULT 30;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS password_min_length int DEFAULT 8;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS password_max_length int DEFAULT 128;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS assistant_max_length int DEFAULT 2000;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS assistant_min_length int DEFAULT 20;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS assistant_description_max int DEFAULT 2000;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS assistant_photo_max int DEFAULT 2048;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS assistant_top_items int DEFAULT 3;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS export_inline_max_bytes bigint DEFAULT 102400;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS export_expires_in_seconds int DEFAULT 900;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS ws_read_limit int DEFAULT 4096;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS ws_read_deadline_seconds int DEFAULT 60;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS ws_ping_interval_seconds int DEFAULT 30;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS ws_write_deadline_seconds int DEFAULT 10;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS location_sync_interval_seconds int DEFAULT 5;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS settings_refresh_interval_minutes int DEFAULT 5;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS idempotency_cleanup_interval_minutes int DEFAULT 10;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS event_poll_timeout_seconds int DEFAULT 25;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS active_sessions_interval_seconds int DEFAULT 15;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS default_trip_list_limit int DEFAULT 20;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS default_webhook_deliveries_limit int DEFAULT 20;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS max_webhook_deliveries_limit int DEFAULT 100;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS marketing_extra_max_list_limit int DEFAULT 100;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS warehouse_stock_response_limit int DEFAULT 1000;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS admin_extra_max_list_limit int DEFAULT 100;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS admin_config_max_list_limit int DEFAULT 100;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS admin_two_person_list_cap int DEFAULT 25;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS default_admin_list_limit int DEFAULT 20;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS max_admin_list_limit int DEFAULT 100;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS report_list_page_size int DEFAULT 25;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS search_max_query_len int DEFAULT 200;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS default_search_limit int DEFAULT 20;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS max_search_limit int DEFAULT 50;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS rider_ops2_list_page_size int DEFAULT 20;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS rider_ops2_list_max_size int DEFAULT 100;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS payment_history_default_limit int DEFAULT 20;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS payment_history_max_limit int DEFAULT 100;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS assistant_chat_max_message_len int DEFAULT 1000;

-- +goose Down
ALTER TABLE platform_settings DROP COLUMN IF EXISTS pair_code_ttl_minutes;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS birthday_reward_window_days;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS masked_call_ttl_minutes;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS masked_call_gateway_timeout_seconds;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS payment_qr_ttl_minutes;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS throttle_max_attempts;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS throttle_window_minutes;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS check_in_rate_limit;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS check_in_rate_window_hours;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS check_in_redis_ttl_hours;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS dispatch_offer_expiry_minutes;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS default_campaign_duration_days;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS password_min_length;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS password_max_length;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS assistant_max_length;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS assistant_min_length;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS assistant_description_max;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS assistant_photo_max;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS assistant_top_items;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS export_inline_max_bytes;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS export_expires_in_seconds;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS ws_read_limit;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS ws_read_deadline_seconds;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS ws_ping_interval_seconds;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS ws_write_deadline_seconds;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS location_sync_interval_seconds;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS settings_refresh_interval_minutes;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS idempotency_cleanup_interval_minutes;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS event_poll_timeout_seconds;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS active_sessions_interval_seconds;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS default_trip_list_limit;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS default_webhook_deliveries_limit;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS max_webhook_deliveries_limit;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS marketing_extra_max_list_limit;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS warehouse_stock_response_limit;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS admin_extra_max_list_limit;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS admin_config_max_list_limit;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS admin_two_person_list_cap;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS default_admin_list_limit;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS max_admin_list_limit;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS report_list_page_size;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS search_max_query_len;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS default_search_limit;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS max_search_limit;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS rider_ops2_list_page_size;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS rider_ops2_list_max_size;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS payment_history_default_limit;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS payment_history_max_limit;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS assistant_chat_max_message_len;
