-- +goose Up
-- Add columns for all configurable settings
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS two_person_threshold_tzs bigint DEFAULT 5000000;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS withdrawal_minimum_tzs bigint DEFAULT 5000;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS withdrawal_daily_limit int DEFAULT 3;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS withdrawal_rate_window_hours int DEFAULT 24;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS wallet_topup_minimum_tzs bigint DEFAULT 1000;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS admin_rest_enforce_hours int DEFAULT 8;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS default_country text DEFAULT 'TZ';
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS export_base_url text DEFAULT 'https://api.hudumika.app';
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS store_qr_prefix text DEFAULT 'https://hudumika.app/qr/';
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS csp_connect_src text DEFAULT 'connect-src ''self'' ws: wss:';
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS idempotency_ttl_hours int DEFAULT 24;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS export_ttl_hours int DEFAULT 24;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS max_import_rows int DEFAULT 500;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS max_body_bytes bigint DEFAULT 1048576;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS trace_sample_ratio double precision DEFAULT 0.1;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS health_check_timeout_seconds int DEFAULT 5;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS health_monitor_interval_seconds int DEFAULT 30;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS event_poll_interval_ms int DEFAULT 2000;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS chat_message_rate_limit int DEFAULT 20;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS rider_location_rate_limit int DEFAULT 12;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS auth_rate_limit int DEFAULT 10;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS global_rate_limit int DEFAULT 100;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS verification_rate_limit int DEFAULT 20;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS pair_code_ttl_minutes int DEFAULT 10;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS account_deletion_grace_days int DEFAULT 30;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS default_estimate_duration_minutes int DEFAULT 60;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS compliance_estimated_minutes int DEFAULT 30;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS max_receipt_templates int DEFAULT 10;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS max_payment_accounts int DEFAULT 5;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS min_self_pickup_minutes int DEFAULT 5;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS max_self_pickup_minutes int DEFAULT 120;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS chat_max_message_length int DEFAULT 2000;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS default_chat_list_limit int DEFAULT 20;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS max_chat_list_limit int DEFAULT 50;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS default_home_feed_limit int DEFAULT 100;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS tracking_share_expiry_hours int DEFAULT 2;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS rider_share_expiry_hours int DEFAULT 24;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS export_rate_limit int DEFAULT 3;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS degradation_threshold_slow_ms int DEFAULT 100;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS degradation_threshold_degraded_ms int DEFAULT 500;
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS degradation_threshold_critical_ms int DEFAULT 2000;

-- +goose Down
ALTER TABLE platform_settings DROP COLUMN IF EXISTS two_person_threshold_tzs;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS withdrawal_minimum_tzs;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS withdrawal_daily_limit;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS withdrawal_rate_window_hours;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS wallet_topup_minimum_tzs;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS admin_rest_enforce_hours;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS default_country;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS export_base_url;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS store_qr_prefix;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS csp_connect_src;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS idempotency_ttl_hours;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS export_ttl_hours;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS max_import_rows;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS max_body_bytes;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS trace_sample_ratio;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS health_check_timeout_seconds;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS health_monitor_interval_seconds;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS event_poll_interval_ms;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS chat_message_rate_limit;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS rider_location_rate_limit;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS auth_rate_limit;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS global_rate_limit;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS verification_rate_limit;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS pair_code_ttl_minutes;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS account_deletion_grace_days;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS default_estimate_duration_minutes;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS compliance_estimated_minutes;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS max_receipt_templates;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS max_payment_accounts;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS min_self_pickup_minutes;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS max_self_pickup_minutes;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS chat_max_message_length;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS default_chat_list_limit;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS max_chat_list_limit;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS default_home_feed_limit;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS tracking_share_expiry_hours;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS rider_share_expiry_hours;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS export_rate_limit;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS degradation_threshold_slow_ms;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS degradation_threshold_degraded_ms;
ALTER TABLE platform_settings DROP COLUMN IF EXISTS degradation_threshold_critical_ms;
